spring:
  application:
    name: HospitalService-FeignClient

eureka: 
  client: 
    serviceUrl: 
       defaultZone: ${EUREKA_URI:http://localhost:9090/eureka/}
  instance:
    prefer-ip-address: true
    home-page-url: http://localhost:9090/
    
server:
  port: 8181
