spring:
  application:
    name: CustomerService
    
  cloud:
    zookeeper:
      discovery:
        instance-id: ${spring.application.name}
        
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testflyway
    username: sai
    password: sai
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      
      
server:
  port: 8585