spring:
  application:
    name: PatientService
  h2:
    console:
      enabled: true
eureka: 
  client: 
    enabled: true
    serviceUrl: 
       defaultZone: ${EUREKA_URI:http://localhost:9090/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    home-page-url: http://eureka:9090/
    hostname: localhost
    
    
server:
  port: ${portno:9191}
  